2024-12-11 16:28:55,736 - INFO - Polling stopped
2024-12-11 16:28:55,998 - INFO - Polling stopped for bot @ParseNews111_bot id=7896089910 - 'ParseNewsBot001'
2024-12-11 16:29:00,611 - DEBUG - Using proactor: IocpProactor
2024-12-11 16:29:00,793 - INFO - Start polling
2024-12-11 16:29:00,841 - INFO - Run polling for bot @ParseNews111_bot id=7896089910 - 'ParseNewsBot001'
2024-12-11 16:30:17,296 - INFO - Пользователь вызвал /start
2024-12-11 16:30:17,520 - INFO - Update id=170865408 is handled. Duration 219 ms by bot id=7896089910
2024-12-11 16:30:18,555 - INFO - Загрузка новостей для категории: tech_news
2024-12-11 16:30:18,557 - DEBUG - Starting new HTTPS connection (1): 3dnews.ru:443
2024-12-11 16:30:18,905 - DEBUG - https://3dnews.ru:443 "GET /tags/%D0%B8%D0%B8 HTTP/11" 200 None
2024-12-11 16:30:19,005 - DEBUG - Новости для tech_news: [{'title': '«Нам нужно генерировать прибыль»: Google нарастит присутствие ИИ в поиске', 'url': 'https://3dnews.ru/1115281', 'image': 'https://3dnews.ru/assets/external/illustrations/2024/12/11/1115281/google.jpg', 'likes': None, 'date': '11.12.2024[15:48],Павел Котов'}, {'title': 'ИИ отправит на свалку истории поисковики и браузеры, считает глава Microsoft AI', 'url': 'https://3dnews.ru/1115277', 'image': 'https://3dnews.ru/assets/external/illustrations/2024/12/11/1115277/811.jpg', 'likes': None, 'date': '11.12.2024[14:42],Владимир Фетисов'}, {'title': 'Миллионы роликов на YouTube получат дубляж на иностранных языках', 'url': 'https://3dnews.ru/1115255', 'image': 'https://3dnews.ru/assets/external/illustrations/2024/12/11/1115255/youtube_01.jpg', 'likes': None, 'date': '11.12.2024[08:27],Алексей Разин'}, {'title': 'OpenAI запустила ИИ-генератор видео по текстовым запросам Sora\xa0— он косячит так же, как и другие', 'url': 'https://3dnews.ru/1115194', 'image': 'https://3dnews.ru/assets/external/illustrations/2024/12/10/1115194/sm.sora_01.800.jpg', 'likes': None, 'date': '10.12.2024[01:30],Андрей Созинов'}, {'title': 'ИИ-система производителя игрушек Funko вывела из строя сайт платформы itch.io', 'url': 'https://3dnews.ru/1115180', 'image': 'https://3dnews.ru/assets/external/illustrations/2024/12/09/1115180/00.jpg', 'likes': None, 'date': '09.12.2024[19:35],Дмитрий Рудь'}, {'title': 'Разработчик чипов Marvell Technology стал дороже Intel благодаря ИИ-буму', 'url': 'https://3dnews.ru/1115170', 'image': 'https://3dnews.ru/assets/external/illustrations/2024/12/09/1115170/marvell-technology-prevzoshla-intel-po-kapitalizatsii-na-fone-vzrivnogo-rosta-dohodov-ot-datatsentrov-main.jpg', 'likes': None, 'date': '09.12.2024[16:18],Дмитрий Федоров'}, {'title': 'Китай ускорил локализацию полупроводников и за полгода потратил на это больше, чем США, Корея и Тайвань вместе', 'url': 'https://3dnews.ru/1115162', 'image': 'https://3dnews.ru/assets/external/illustrations/2024/12/09/1115162/kitay-uskoril-lokalizatsiyu-poluprovodnikovoy-otrasli-i-za-polgoda-investiroval-v-neyo-rekordnie-25-mlrd-main.jpg', 'likes': None, 'date': '09.12.2024[14:16],Дмитрий Федоров'}, {'title': 'Новая статья: ИИтоги ноября 2024 г.: неужто чижик?', 'url': 'https://3dnews.ru/1115146', 'image': None, 'likes': None, 'date': '09.12.2024[00:03],3DNews Team'}, {'title': 'Чат-бот Grok от xAI Илона Маска обзавёлся генератором фотореалистичных изображений', 'url': 'https://3dnews.ru/1115124', 'image': 'https://3dnews.ru/assets/external/illustrations/2024/12/08/1115124/grok_01.jpg', 'likes': None, 'date': '08.12.2024[06:24],Алексей Разин'}, {'title': 'ИИ-бота взломали и убедили отдать деньги методом мошенников из «службы безопасности банка»', 'url': 'https://3dnews.ru/1115105', 'image': 'https://3dnews.ru/assets/external/illustrations/2024/12/07/1115105/freysa_1.jpg', 'likes': None, 'date': '07.12.2024[13:42],Павел Котов'}]
2024-12-11 16:30:19,005 - DEBUG - Показ новости 0: {'title': '«Нам нужно генерировать прибыль»: Google нарастит присутствие ИИ в поиске', 'url': 'https://3dnews.ru/1115281', 'image': 'https://3dnews.ru/assets/external/illustrations/2024/12/11/1115281/google.jpg', 'likes': None, 'date': '11.12.2024[15:48],Павел Котов'}
2024-12-11 16:30:19,280 - INFO - Update id=170865409 is handled. Duration 718 ms by bot id=7896089910
2024-12-11 16:30:20,498 - INFO - Update id=170865410 is not handled. Duration 0 ms by bot id=7896089910
2024-12-11 16:30:20,498 - ERROR - Cause exception while process update id=170865410 by bot id=7896089910
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\HDL\CascadeProjects\NewsBot\bot.py", line 126, in paginate_news
    action, category = callback.data.split("_")
    ^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
2024-12-11 16:30:28,526 - INFO - Пользователь вернулся в меню
2024-12-11 16:30:28,578 - INFO - Update id=170865411 is not handled. Duration 46 ms by bot id=7896089910
2024-12-11 16:30:28,578 - ERROR - Cause exception while process update id=170865411 by bot id=7896089910
TelegramBadRequest: Telegram server says - Bad Request: there is no text in the message to edit
Traceback (most recent call last):
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\HDL\CascadeProjects\NewsBot\bot.py", line 59, in show_menu
    await callback.message.edit_text("Выбери категорию:", reply_markup=get_main_menu())
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\client\bot.py", line 494, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: there is no text in the message to edit
2024-12-11 16:30:30,604 - INFO - Update id=170865412 is not handled. Duration 0 ms by bot id=7896089910
2024-12-11 16:30:30,604 - ERROR - Cause exception while process update id=170865412 by bot id=7896089910
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\HDL\CascadeProjects\NewsBot\bot.py", line 126, in paginate_news
    action, category = callback.data.split("_")
    ^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
2024-12-11 16:30:33,705 - INFO - Пользователь вызвал /start
2024-12-11 16:30:33,784 - INFO - Update id=170865413 is handled. Duration 78 ms by bot id=7896089910
2024-12-11 16:30:34,635 - INFO - Загрузка новостей для категории: game_news
2024-12-11 16:30:34,636 - DEBUG - Starting new HTTPS connection (1): www.playground.ru:443
2024-12-11 16:30:34,902 - DEBUG - https://www.playground.ru:443 "GET /news HTTP/11" 200 None
2024-12-11 16:30:34,946 - DEBUG - Новости для game_news: [{'title': 'В патче 2.2 для Cyberpunk 2077 добавили кастомизацию авто в реальном времени, улучшили редактор и многое другое', 'url': 'https://www.playground.ru/cyberpunk_2077/news/v_patche_2_2_dlya_cyberpunk_2077_dobavili_kastomizatsiyu_avto_v_realnom_vremeni_uluchshili_redaktor_i_mnogoe_drugoe-1739898', 'image': 'https://i.playground.ru/e/UcrUyLavKFeXMBth7Cm03g.png?392x220', 'likes': None, 'date': 'вчера в 20:13|Обновления'}, {'title': 'Датамайнеры Marvel Rivals обнаружили, что модели слишком детализированы - разработчики явно не против видео для взрослых', 'url': 'https://www.playground.ru/marvel_rivals/news/datamajnery_marvel_rivals_obnaruzhili_chto_modeli_slishkom_detalizirovany_razrabotchiki_yavno_ne_protiv_video_dlya_vzroslyh-1740029', 'image': 'https://i.playground.ru/e/2gRsw_HhaTncPwEyjqVc2g.jpeg?392x220', 'likes': None, 'date': 'сегодня в 13:14|Индустрия'}, {'title': 'Российский постапокалиптический шутер Pioner получил новый геймплейный трейлер и обзавёлся страницей в Steam', 'url': 'https://www.playground.ru/pioner/news/rossijskij_postapokalipticheskij_shuter_pioner_poluchil_novyj_gejmplejnyj_trejler_i_obzavyolsya_stranitsej_v_steam-1739876', 'image': 'https://i.playground.ru/e/V_E3gtFf4Ehx7kkSbPrqvA.jpeg?392x220', 'likes': None, 'date': 'вчера в 18:18|Трейлеры'}, {'title': 'Третье DLC для Atomic Heart: "Чары морских глубин" получило новый трейлер и дату выхода', 'url': 'https://www.playground.ru/atomic_heart/news/trete_dlc_dlya_atomic_heart_chary_morskih_glubin_poluchilo_novyj_trejler_i_datu_vyhoda-1739701', 'image': 'https://i.playground.ru/e/ivexEtdKEaDRwK6XOE7xsA.png?392x220', 'likes': None, 'date': '9 декабря|Трейлеры'}, {'title': 'CDPR предложила опцию отката до версии 2.13 в Cyberpunk 2077, чтобы игроки могли играть с необновленными модами', 'url': 'https://www.playground.ru/cyberpunk_2077/news/cdpr_predlozhila_optsiyu_otkata_do_versii_2_13_v_cyberpunk_2077_chtoby_igroki_mogli_igrat_s_neobnovlennymi_modami-1739996', 'image': 'https://i.playground.ru/e/-1GLEQChtuYWns0B6ANUmQ.jpeg?392x220', 'likes': None, 'date': 'сегодня в 11:09|ПК'}, {'title': 'YouTube запустил автоматический дубляж видео с помощью ИИ для сотен тысяч образовательных каналов', 'url': 'https://www.playground.ru/misc/news/youtube_zapustil_avtomaticheskij_dublyazh_video_s_pomoschyu_ii_dlya_soten_tysyach_obrazovatelnyh_kanalov-1739971', 'image': 'https://i.playground.ru/e/evxrIipges8sKMrl-ElHTQ.jpeg?392x220', 'likes': None, 'date': 'сегодня в 09:18|Технологии'}, {'title': 'Развлекательный портал PornHub опубликовал список самых популярных героинь из игр 2024 года', 'url': 'https://www.playground.ru/misc/news/razvlekatelnyj_portal_pornhub_opublikoval_spisok_samyh_populyarnyh_geroin_iz_igr_2024_goda-1739900', 'image': 'https://i.playground.ru/e/0_kIi4Cu4ycvZXSojxpoyA.jpeg?392x220', 'likes': None, 'date': 'вчера в 20:20|Индустрия'}, {'title': 'Поклонники, узнав о разработке GTA 6 и ее сценаристах, стали нервничать и даже пригрозили отказаться от игры', 'url': 'https://www.playground.ru/gta_6/news/poklonniki_uznav_o_razrabotke_gta_6_i_ee_stsenaristah_stali_nervnichat_i_dazhe_prigrozili_otkazatsya_ot_igry-1739788', 'image': 'https://i.playground.ru/e/mTyZc9n5jwWdbcrcYRLF5A.jpeg?392x220', 'likes': None, 'date': 'вчера в 10:16'}, {'title': 'Sony представила атмосферный трейлер фильма "28 лет спустя"', 'url': 'https://www.playground.ru/misc/news/sony_predstavila_atmosfernyj_trejler_filma_28_let_spustya-1739797', 'image': 'https://i.playground.ru/e/RtmKdrWe86dykhZFAv8scA.jpeg?392x220', 'likes': None, 'date': 'вчера в 11:19|Кино и сериалы,Трейлеры'}, {'title': 'CD Projekt RED готовит еще одно неожиданное обновление для Cyberpunk 2077', 'url': 'https://www.playground.ru/cyberpunk_2077/news/cd_projekt_red_gotovit_esche_odno_neozhidannoe_obnovlenie_dlya_cyberpunk_2077-1739705', 'image': 'https://i.playground.ru/e/AGHtVk5a7tGphZO9YZOHWw.png?392x220', 'likes': None, 'date': '9 декабря|Обновления'}]
2024-12-11 16:30:34,946 - DEBUG - Показ новости 0: {'title': 'В патче 2.2 для Cyberpunk 2077 добавили кастомизацию авто в реальном времени, улучшили редактор и многое другое', 'url': 'https://www.playground.ru/cyberpunk_2077/news/v_patche_2_2_dlya_cyberpunk_2077_dobavili_kastomizatsiyu_avto_v_realnom_vremeni_uluchshili_redaktor_i_mnogoe_drugoe-1739898', 'image': 'https://i.playground.ru/e/UcrUyLavKFeXMBth7Cm03g.png?392x220', 'likes': None, 'date': 'вчера в 20:13|Обновления'}
2024-12-11 16:30:35,119 - INFO - Update id=170865414 is handled. Duration 484 ms by bot id=7896089910
2024-12-11 16:30:36,050 - INFO - Update id=170865415 is not handled. Duration 0 ms by bot id=7896089910
2024-12-11 16:30:36,050 - ERROR - Cause exception while process update id=170865415 by bot id=7896089910
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HDL\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\HDL\CascadeProjects\NewsBot\bot.py", line 126, in paginate_news
    action, category = callback.data.split("_")
    ^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
2024-12-11 16:30:46,056 - INFO - Update id=170865416 is not handled. Duration 0 ms by bot id=7896089910
2024-12-11 16:31:15,542 - INFO - Polling stopped
2024-12-11 16:31:15,805 - INFO - Polling stopped for bot @ParseNews111_bot id=7896089910 - 'ParseNewsBot001'
2024-12-11 16:32:25,957 - DEBUG - Using proactor: IocpProactor
2024-12-11 16:32:26,113 - INFO - Start polling
2024-12-11 16:32:26,169 - INFO - Run polling for bot @ParseNews111_bot id=7896089910 - 'ParseNewsBot001'
2024-12-11 16:32:46,309 - INFO - Polling stopped
2024-12-11 16:32:46,565 - INFO - Polling stopped for bot @ParseNews111_bot id=7896089910 - 'ParseNewsBot001'
